### ISSUE TITLE
Install button is one-use-only

### ISSUE THREAD

**Issue by ShadyMedic** [nullTheCoder/500mb_jar_installer#1]
After selecting a version and a path to a file that already exists, a confirmation dialogue pops up. If I don't confirm the overwrite of the original file, the `Install` button is no longer reacting.

**Comment by nullTheCoder** [comment]
Fixed. Install button should work now after finishing a download.

**Comment by ShadyMedic** [comment]
Not fixed. The install button might work when the installation is finished, however, the problem was that it doesn't work if the installation is cancelled (by denying the old file's overwrite).

The application got to a weird frozen-like state, that I had to kill it with a command prompt after finding out its process ID.

**Comment by nullTheCoder** [comment]
The cause of the problem was fixed with the most recent commit.

**Comment by ShadyMedic** [comment]
Good work, when I select "No" in the dialogue box, the install button keeps working.

However, with the implementation of the cancel button, the button remains "deaf" after it replaces the clicked "Cancel" button.

**Comment by nullTheCoder** [comment]
Now it should work
